general:
steps:
  gctsDeploy:
    host: 'https://bestia.xrsc.com:8000'
    client: '400'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'gctsR'
    remoteRepositoryURL: "https://remote.repository.url.com"
    role: 'SOURCE'
    vSID: 'ABC'
    branch: 'feature1'
    commit: '0c9d330'
    scope: 'CRNTCOMMIT'
    rollback: false
    configuration:
        VCS_AUTOMATIC_PULL: "FALSE"
        VCS_AUTOMATIC_PUSH: "FALSE"
        CLIENT_VCS_LOGLVL: "debug"
